[package]
name = "rubiks_sim"
version = "0.2.0"
edition = "2024"

[lib]
name = "rubiks_sim"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rubiks_sim"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_ui",
    "default_font",
    "x11",
    "tonemapping_luts",
    "png",
] }
rand = "0.8"
image = { version = "0.24", default-features = false, features = ["png"] }
winit = { version = "0.29", default-features = false }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[target.'cfg(target_os = "android")'.dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_ui",
    "default_font",
    "tonemapping_luts",
    "png",
    "android_shared_stdcxx",
] }

[package.metadata.android]
package = "com.vitorpaiva.rubikssim"
apk_name = "rubiks_sim"
assets = "assets"
res = "res"
min_sdk_version = 24
target_sdk_version = 34
opengles_version = "0x00030000"

[package.metadata.android.application]
label = "Rubik's Cube 3D"
icon = "@mipmap/ic_launcher"

[package.metadata.android.activity]
orientation = "unspecified"